import { BarChart3, FileSearch, Gauge, Scale, ShieldCheck, TriangleAlert } from 'lucide-react'
import SiteFrame from '../../components/SiteFrame'
import styles from '../../core-v4.module.css'
import local from '../ipo.module.css'

export const metadata = {
  title: 'IPO Data Score Methodology',
  description:
    'How CredoNomics normalizes public-offer financial data and calculates its fixed quantitative IPO Data Score.',
  alternates: { canonical: '/ipo/methodology' },
}

const weights = [
  ['Revenue CAGR', '12', 'Mechanical multi-period revenue growth.'],
  ['PAT CAGR', '12', 'Mechanical multi-period positive PAT growth.'],
  ['ROE', '10', 'Latest normalized return on equity.'],
  ['ROCE', '10', 'Latest normalized return on capital employed.'],
  ['CFO / PAT', '12', 'Cash conversion relative to accounting profit.'],
  ['Debt / Equity', '10', 'Lower leverage scores higher mechanically.'],
  ['P/E vs peer median', '14', 'Upper-band IPO P/E relative to normalized listed peers.'],
  ['P/B vs peer median', '6', 'Upper-band IPO P/B relative to normalized listed peers.'],
  ['Fresh-issue share', '7', 'Fresh capital as a percentage of total issue size.'],
  ['OFS share', '4', 'Lower OFS share scores higher mechanically.'],
  ['Top-customer concentration', '3', 'Lower disclosed revenue concentration scores higher.'],
]

export default function IpoMethodologyPage() {
  return (
    <SiteFrame>
      <section className={`${styles.wrap} ${styles.pageHero}`}>
        <div className={styles.breadcrumbs}><a href="/">Home</a><span>/</span><a href="/ipo">IPO Intelligence</a><span>/</span><span>Methodology</span></div>
        <span className={styles.pageKicker}><Gauge size={14}/> Public quantitative methodology</span>
        <h1>The score is only useful if the <span>formula stays visible.</span></h1>
        <p className={styles.pageHeroLead}>
          CredoNomics uses a fixed statistical model with explicit weights. No hidden analyst override
          changes the result, and missing inputs reduce visible data coverage.
        </p>
      </section>

      <section className={`${styles.wrap} ${styles.pageBody} ${local.shell}`}>
        <div className={local.methodIntro}>
          <article><FileSearch size={20}/><h2>Source first</h2><p>Normalize from the current DRHP/RHP/prospectus and relevant exchange/registrar documents. Discovery records alone are never scored.</p></article>
          <article><BarChart3 size={20}/><h2>Statistical fields</h2><p>The model uses financial growth, return ratios, cash conversion, leverage, peer-relative valuation and issue structure.</p></article>
          <article><Scale size={20}/><h2>Coverage threshold</h2><p>No public score is produced when less than 50 weighted points of the framework have valid normalized data.</p></article>
        </div>

        <section className={local.featureSection}>
          <div className={local.sectionHead}><div><span>100-point framework</span><h2>Fixed weights used by the IPO Data Score.</h2></div></div>
          <div className={local.weightTable}>
            {weights.map(([label, weight, note]) => (
              <div key={label}>
                <strong>{weight}</strong>
                <span><b>{label}</b><small>{note}</small></span>
              </div>
            ))}
          </div>
        </section>

        <section className={local.methodBoundary}>
          <ShieldCheck size={23}/>
          <div>
            <small>Important boundary</small>
            <h2>A high Data Score is not “Subscribe.” A low score is not “Avoid.”</h2>
            <p>
              The score is a mechanical statistical comparison of normalized inputs. It does not
              estimate listing gains, future share returns, allotment probability or suitability for a particular investor.
            </p>
          </div>
        </section>

        <section className={local.featureSection}>
          <div className={local.sectionHead}><div><span>What stays outside the score</span><h2>Signals that should not be mixed into fundamental data quality.</h2></div></div>
          <div className={local.exclusionGrid}>
            <article><TriangleAlert size={18}/><h3>Grey Market Premium</h3><p>GMP is unofficial and is not included in the fundamental Data Score.</p></article>
            <article><TriangleAlert size={18}/><h3>Subscription multiples</h3><p>Subscription data can be displayed separately, but does not change the core financial Data Score.</p></article>
            <article><TriangleAlert size={18}/><h3>Listing-gain forecasts</h3><p>No predicted listing price or return is generated by the scoring framework.</p></article>
            <article><TriangleAlert size={18}/><h3>Subscribe / Avoid calls</h3><p>CredoNomics does not convert the statistical score into a public-offer recommendation.</p></article>
          </div>
        </section>

        <div className={local.regulatoryNotice}>
          <ShieldCheck size={20}/>
          <p>
            CredoNomics is not SEBI-registered and is not NISM-certified. This methodology is designed
            for general educational/statistical comparison. Seek appropriately registered professional advice
            where a securities recommendation or personalized advice is required.
          </p>
        </div>
      </section>
    </SiteFrame>
  )
}
