// AUTO-GENERATED by scripts/ipo/refresh-ipo-market-master.mjs.
// Exchange-market layer: issue status/dates/price/subscription. Not a fundamental score.

import type { IpoMarketRecord } from './ipo-types'

export const ipoMarketMasterMeta = {
  "generatedAt": "2026-08-25T10:57:18.466Z",
  "recordCount": 8,
  "nseCount": 8,
  "bseCount": 0,
  "activeCount": 8,
  "upcomingCount": 0,
  "sourceStatus": "NSE API 8 · BSE SME unavailable · BSE mainboard 0"
} as const

export const ipoMarketMaster: IpoMarketRecord[] = [
  {
    "slug": "augmont-enterprises-ltd-561dd1f",
    "companyName": "Augmont Enterprises Limited",
    "symbol": "AUGMONT",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 750,
      "priceBandHigh": 788,
      "openDate": "2026-08-21",
      "closeDate": "2026-08-25",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 79.61859676238942,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=AUGMONT&type=Active"
    },
    "sharesOffered": 7715999,
    "sharesBid": 614337013,
    "estimatedIssueValueCr": 608.02,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=AUGMONT&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "abh-healthcare-ltd-9013175",
    "companyName": "ABH Healthcare Limited",
    "symbol": "ABH",
    "marketSegment": "sme",
    "status": "open",
    "securityType": "SME",
    "issue": {
      "openDate": "2026-08-24",
      "closeDate": "2026-08-27",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.83,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=ABH&type=Active"
    },
    "sharesOffered": 3429600,
    "sharesBid": 2839200,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=ABH&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "hy-tech-engineers-ltd-9057d1b",
    "companyName": "Hy-Tech Engineers Limited",
    "symbol": "HTEL",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 50,
      "priceBandHigh": 53,
      "openDate": "2026-08-24",
      "closeDate": "2026-08-27",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 12.079049374811454,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=HTEL&type=Active"
    },
    "sharesOffered": 18145406,
    "sharesBid": 219179255,
    "estimatedIssueValueCr": 96.17,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=HTEL&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "madhur-knit-crafts-ltd-9d0b8dd",
    "companyName": "Madhur Knit Crafts Limited",
    "symbol": "MADHURKNIT",
    "marketSegment": "sme",
    "status": "open",
    "securityType": "SME",
    "issue": {
      "openDate": "2026-08-24",
      "closeDate": "2026-08-27",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.43,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=MADHURKNIT&type=Active"
    },
    "sharesOffered": 5024400,
    "sharesBid": 2160000,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=MADHURKNIT&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "skyways-air-services-ltd-80753ac",
    "companyName": "Skyways Air Services Limited",
    "symbol": "SKYWAYS",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 131,
      "priceBandHigh": 138,
      "openDate": "2026-08-24",
      "closeDate": "2026-08-27",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 1.5435038332048838,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SKYWAYS&type=Active"
    },
    "sharesOffered": 29583600,
    "sharesBid": 45662400,
    "estimatedIssueValueCr": 408.25,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SKYWAYS&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "symbiotec-pharmalab-ltd-1e6db9d",
    "companyName": "Symbiotec Pharmalab Limited",
    "symbol": "SYMBIOTEC",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 938,
      "priceBandHigh": 988,
      "openDate": "2026-08-24",
      "closeDate": "2026-08-27",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 1.266045705847247,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SYMBIOTEC&type=Active"
    },
    "sharesOffered": 13124929,
    "sharesBid": 16616760,
    "estimatedIssueValueCr": 1296.74,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SYMBIOTEC&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "annu-projects-ltd-c8948a3",
    "companyName": "Annu Projects Limited",
    "symbol": "ANNU",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 94,
      "priceBandHigh": 99,
      "openDate": "2026-08-25",
      "closeDate": "2026-08-28",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.21881892212859808,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=ANNU&type=Active"
    },
    "sharesOffered": 17683000,
    "sharesBid": 3869375,
    "estimatedIssueValueCr": 175.06,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=ANNU&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  },
  {
    "slug": "sumax-engineering-ltd-6a15dfb",
    "companyName": "Sumax Engineering Limited",
    "symbol": "SUMAX",
    "marketSegment": "sme",
    "status": "open",
    "securityType": "SME",
    "issue": {
      "openDate": "2026-08-25",
      "closeDate": "2026-08-28",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 2.6,
      "updatedAt": "2026-08-25T10:57:18.466Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=SUMAX&type=Active"
    },
    "sharesOffered": 3852000,
    "sharesBid": 10008000,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=SUMAX&type=Active",
    "fetchedAt": "2026-08-25T10:57:18.466Z"
  }
]
