// AUTO-GENERATED by scripts/ipo/refresh-ipo-market-master.mjs.
// Exchange-market layer: issue status/dates/price/subscription. Not a fundamental score.

import type { IpoMarketRecord } from './ipo-types'

export const ipoMarketMasterMeta = {
  "generatedAt": "2026-09-10T13:34:12.284Z",
  "recordCount": 11,
  "nseCount": 11,
  "bseCount": 0,
  "activeCount": 11,
  "upcomingCount": 0,
  "sourceStatus": "NSE API 11 · BSE SME unavailable · BSE mainboard 0"
} as const

export const ipoMarketMaster: IpoMarketRecord[] = [
  {
    "slug": "glass-wall-systems-india-ltd-e0ba777",
    "companyName": "Glass Wall Systems (India) Limited",
    "symbol": "GLASSWALL",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 172,
      "priceBandHigh": 182,
      "openDate": "2026-09-08",
      "closeDate": "2026-09-10",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 56.5945909225196,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=GLASSWALL&type=Active"
    },
    "sharesOffered": 16457298,
    "sharesBid": 931394048,
    "estimatedIssueValueCr": 299.52,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=GLASSWALL&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "kanohar-electricals-ltd-3cc51df",
    "companyName": "Kanohar Electricals Limited",
    "symbol": "KANOHAR",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 601,
      "priceBandHigh": 632,
      "openDate": "2026-09-08",
      "closeDate": "2026-09-10",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 69.53480737644705,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=KANOHAR&type=Active"
    },
    "sharesOffered": 11693326,
    "sharesBid": 813093171,
    "estimatedIssueValueCr": 739.02,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=KANOHAR&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "prasol-chemicals-ltd-4fdf230",
    "companyName": "Prasol Chemicals Limited",
    "symbol": "PRASOLCHEM",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 643,
      "priceBandHigh": 676,
      "openDate": "2026-09-08",
      "closeDate": "2026-09-10",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 1.5246817651801898,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=PRASOLCHEM&type=Active"
    },
    "sharesOffered": 5443229,
    "sharesBid": 8299192,
    "estimatedIssueValueCr": 367.96,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=PRASOLCHEM&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "asset-reconstruction-company-india-ltd-1a3e0b1",
    "companyName": "Asset Reconstruction Company (India) Limited",
    "symbol": "ARCIL",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 132,
      "priceBandHigh": 139,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.5997211015723919,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=ARCIL&type=Active"
    },
    "sharesOffered": 36912363,
    "sharesBid": 22137123,
    "estimatedIssueValueCr": 513.08,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=ARCIL&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "karamtara-engineering-ltd-65947d6",
    "companyName": "Karamtara Engineering Limited",
    "symbol": "KARAMTARA",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 241,
      "priceBandHigh": 254,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 2.426116657302751,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=KARAMTARA&type=Active"
    },
    "sharesOffered": 25414937,
    "sharesBid": 61659602,
    "estimatedIssueValueCr": 645.54,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=KARAMTARA&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "lcc-projects-ltd-bfa4468",
    "companyName": "LCC Projects Limited",
    "symbol": "LCCPROJECT",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 139,
      "priceBandHigh": 146,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 3.0067492284353614,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=LCCPROJECT&type=Active"
    },
    "sharesOffered": 20927281,
    "sharesBid": 62923086,
    "estimatedIssueValueCr": 305.54,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=LCCPROJECT&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "manipal-payment-and-identity-solutions-ltd-dbca562",
    "companyName": "Manipal Payment and Identity Solutions Limited",
    "symbol": "MPIMANIPAL",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 322,
      "priceBandHigh": 339,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.20091708783572293,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=MPIMANIPAL&type=Active"
    },
    "sharesOffered": 13060472,
    "sharesBid": 2624072,
    "estimatedIssueValueCr": 442.75,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=MPIMANIPAL&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "rentomojo-ltd-766dbd9",
    "companyName": "Rentomojo Limited",
    "symbol": "RENTOMOJO",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 384,
      "priceBandHigh": 404,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 3.3707126909954575,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=RENTOMOJO&type=Active"
    },
    "sharesOffered": 21772311,
    "sharesBid": 73388205,
    "estimatedIssueValueCr": 879.6,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=RENTOMOJO&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "steamhouse-india-ltd-7be6b43",
    "companyName": "Steamhouse India Limited",
    "symbol": "STEAMHOUSE",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 77,
      "priceBandHigh": 81,
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 1.2811947318076404,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=STEAMHOUSE&type=Active"
    },
    "sharesOffered": 37636363,
    "sharesBid": 48219510,
    "estimatedIssueValueCr": 304.85,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=STEAMHOUSE&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "vinod-texworld-ltd-0db2335",
    "companyName": "Vinod Texworld Limited",
    "symbol": "VINOD",
    "marketSegment": "sme",
    "status": "open",
    "securityType": "SME",
    "issue": {
      "openDate": "2026-09-09",
      "closeDate": "2026-09-11",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.6,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=VINOD&type=Active"
    },
    "sharesOffered": 4556400,
    "sharesBid": 2725200,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=SME&symbol=VINOD&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  },
  {
    "slug": "veegaland-developers-ltd-b9cfc23",
    "companyName": "Veegaland Developers Limited",
    "symbol": "VEEGALAND",
    "marketSegment": "mainboard",
    "status": "open",
    "securityType": "EQ",
    "issue": {
      "priceBandLow": 130,
      "priceBandHigh": 140,
      "openDate": "2026-09-10",
      "closeDate": "2026-09-15",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.50269984361088,
      "updatedAt": "2026-09-10T13:34:12.284Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=VEEGALAND&type=Active"
    },
    "sharesOffered": 11307692,
    "sharesBid": 5684375,
    "estimatedIssueValueCr": 158.31,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=VEEGALAND&type=Active",
    "fetchedAt": "2026-09-10T13:34:12.284Z"
  }
]
