// AUTO-GENERATED by scripts/ipo/refresh-ipo-market-master.mjs.
// Exchange-market layer: issue status/dates/price/subscription. Not a fundamental score.

import type { IpoMarketRecord } from './ipo-types'

export const ipoMarketMasterMeta = {
  "generatedAt": "2026-10-09T10:27:28.122Z",
  "recordCount": 1,
  "nseCount": 1,
  "bseCount": 0,
  "activeCount": 1,
  "upcomingCount": 0,
  "sourceStatus": "NSE API 1 · BSE SME unavailable · BSE mainboard 0"
} as const

export const ipoMarketMaster: IpoMarketRecord[] = [
  {
    "slug": "smc-global-securities-ltd-86eb7e9",
    "companyName": "SMC Global Securities Limited",
    "symbol": "SMCG04",
    "marketSegment": "unknown",
    "status": "open",
    "securityType": "DEBT",
    "issue": {
      "priceBandLow": 1000,
      "priceBandHigh": 1000,
      "openDate": "2026-10-05",
      "closeDate": "2026-10-09",
      "exchange": [
        "NSE"
      ]
    },
    "subscription": {
      "total": 0.01,
      "updatedAt": "2026-10-09T10:27:28.122Z",
      "sourceUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SMCG04&type=Active"
    },
    "sharesOffered": 750000,
    "sharesBid": 8282,
    "estimatedIssueValueCr": 75,
    "marketSource": "NSE",
    "sourceUrl": "https://www.nseindia.com/market-data/all-upcoming-issues-ipo",
    "issueInfoUrl": "https://www.nseindia.com/market-data/issue-information?series=EQ&symbol=SMCG04&type=Active",
    "fetchedAt": "2026-10-09T10:27:28.122Z"
  }
]
