// AUTO-GENERATED by scripts/ipo/build-verified-ipos.mjs.
// Do not hand-edit. Edit public/data/ipo/verified/*.json and rebuild.

import type { VerifiedIpoRecord } from './ipo-types'

export const VERIFIED_IPO_DATA_DATE = null as string | null
export const verifiedIpos: VerifiedIpoRecord[] = []
