export type PulseQuote = { name: string; symbol: string; instrumentKey: string; price: number | null; change: number | null; changePercent: number | null; volume: number | null; timestamp: string | null }
export type InstitutionalFlow = { label: 'FII' | 'DII'; segment: 'NSE cash'; buy: number; sell: number; net: number; timestamp: string }
export type MarketTrend = { label: string; classification: string; value: number; unit: '%' | 'crore' | 'stocks' }
export type MarketPulse = {
  movers: { gainers: PulseQuote[]; losers: PulseQuote[]; mostActive: PulseQuote[]; universeSize: number }
  breadth: { advances: number; declines: number; unchanged: number; universeSize: number } | null
  sectors: PulseQuote[]
  globals: Array<PulseQuote & { latency: string }>
  flows: InstitutionalFlow[]
  trends: MarketTrend[]
  summary: string[]
  asOf: string | null
}
export function classifyBreadth(quotes: PulseQuote[]) { const valid=quotes.filter(q=>q.change!==null); if(!valid.length)return null; return { advances:valid.filter(q=>q.change!>0).length,declines:valid.filter(q=>q.change!<0).length,unchanged:valid.filter(q=>q.change===0).length,universeSize:valid.length } }
export function buildMarketTrends(indices: PulseQuote[], breadth: MarketPulse['breadth'], flows: InstitutionalFlow[]): MarketTrend[] { const trends:MarketTrend[]=[];for(const name of ['NIFTY 50','BANK NIFTY']){const item=indices.find(x=>x.name===name);if(item?.changePercent!==null&&item?.changePercent!==undefined)trends.push({label:name,classification:item.changePercent>0?'Above previous close':item.changePercent<0?'Below previous close':'At previous close',value:item.changePercent,unit:'%'})}const vix=indices.find(x=>x.name==='INDIA VIX');if(vix?.changePercent!==null&&vix?.changePercent!==undefined)trends.push({label:'India VIX',classification:vix.changePercent>0?'Volatility rising':vix.changePercent<0?'Volatility easing':'Volatility unchanged',value:vix.changePercent,unit:'%'});if(breadth){const net=breadth.advances-breadth.declines;trends.push({label:'Tracked breadth',classification:net>0?'Positive breadth':net<0?'Negative breadth':'Flat breadth',value:net,unit:'stocks'})}for(const item of flows)trends.push({label:`${item.label} net`,classification:item.net>0?'Net buyer':item.net<0?'Net seller':'Neutral',value:item.net,unit:'crore'});return trends }
export function buildPulseSummary(indices: PulseQuote[], sectors: PulseQuote[], breadth: MarketPulse['breadth']): string[] { const sentences:string[]=[];const nifty=indices.find(x=>x.name==='NIFTY 50'),vix=indices.find(x=>x.name==='INDIA VIX');if(nifty?.changePercent!==null&&nifty?.changePercent!==undefined){const leaders=sectors.filter(x=>x.changePercent!==null).sort((a,b)=>b.changePercent!-a.changePercent!).slice(0,2).filter(x=>x.changePercent!>0).map(x=>x.name.replace(/^Nifty /,'')).join(' and ');sentences.push(`NIFTY 50 is ${nifty.changePercent>=0?'up':'down'} ${Math.abs(nifty.changePercent).toFixed(2)}%${leaders?`, with strength in ${leaders}`:''}.`)}if(breadth)sentences.push(`Tracked liquid-stock breadth has ${breadth.advances} advances, ${breadth.declines} declines and ${breadth.unchanged} unchanged.`);if(vix?.changePercent!==null&&vix?.changePercent!==undefined)sentences.push(`India VIX is ${vix.changePercent>0?'up':vix.changePercent<0?'down':'unchanged at'} ${Math.abs(vix.changePercent).toFixed(2)}%.`);return sentences }
