import fs from 'node:fs'
import path from 'node:path'
import { CORE_SCHEMES, MONTH_RE, buildMfTrustMetadata, classifySecurityName, deterministicSort, monthsBetween, normalizeIsin, parseCsv, parsePercentage, resolveSecurityNameByIsin, securityKey, slugify, stableHash, writeJson } from './pipeline-lib.mjs'
const sourceDir=path.resolve('data/mf-production-source'),sourceFile=path.join(sourceDir,'holdings_public.csv'),sourceManifestFile=path.join(sourceDir,'manifest.json'),staging=path.resolve('data/mf-production-staging/v2'),reports=path.resolve('data/mf-production-reports/latest')
const securityMasterFile=path.resolve('public/data/equity/instruments.json'),securityMaster=JSON.parse(fs.readFileSync(securityMasterFile,'utf8')).instruments??[]
const required=['AMC','Report_Date','Report_Month','Scheme','Company','Industry','Portfolio_Weight_Percent','Production_Status','Coverage_Label'],manifest=JSON.parse(fs.readFileSync(sourceManifestFile,'utf8')),sourceText=fs.readFileSync(sourceFile,'utf8'),rows=parseCsv(sourceText)
if(!rows.length||required.some(k=>!(k in rows[0])))throw new Error(`Authoritative source is missing required columns: ${required.filter(k=>!(k in(rows[0]??{}))).join(', ')}`)
const hasIsinColumn=rows.length>0&&('ISIN' in rows[0]);
fs.rmSync(staging,{recursive:true,force:true});fs.rmSync(reports,{recursive:true,force:true})
const aliases=new Map();for(const[scheme,category,names]of CORE_SCHEMES)for(const name of names)aliases.set(name,{scheme,category})
const report={invalidIsins:[],missingIsins:[],contaminatedNames:[],duplicates:[],percentageAnomalies:[],unresolvedRows:[],schemaErrors:[]},stats={sourceRows:rows.length,selectedRows:0,validRows:0,rejectedRows:0,normalizedRows:0,duplicateRows:0,missingIsin:0,invalidIsin:0,validIsin:0},candidates=[]
for(let rowNumber=0;rowNumber<rows.length;rowNumber++){const row=rows[rowNumber],schemeInfo=aliases.get(row.Scheme);if(!schemeInfo||!/^202[56]-/.test(row.Report_Month))continue;stats.selectedRows++;const context={rowNumber:rowNumber+2,scheme:row.Scheme,month:row.Report_Month,company:row.Company};if(!MONTH_RE.test(row.Report_Month)){report.schemaErrors.push({...context,reason:'invalid_month'});stats.rejectedRows++;continue}const name=classifySecurityName(row.Company);if(name.status==='REJECTED'||name.status==='REQUIRES_REVIEW'){report.contaminatedNames.push({...context,status:name.status,reason:name.reason});stats.rejectedRows++;continue}if(name.status==='NORMALIZED')stats.normalizedRows++;const pct=parsePercentage(row.Portfolio_Weight_Percent);if(!pct.ok){report.percentageAnomalies.push({...context,value:row.Portfolio_Weight_Percent,reason:pct.reason});stats.rejectedRows++;continue}const isin=normalizeIsin(row.ISIN);if(isin.status==='MISSING'){stats.missingIsin++;report.missingIsins.push(context)}else if(isin.status==='INVALID'){stats.invalidIsin++;report.invalidIsins.push({...context,value:row.ISIN})}else stats.validIsin++;const resolution=resolveSecurityNameByIsin({sourceSecurityName:name.value,isin:isin.value,instruments:securityMaster});candidates.push({amc:row.AMC,scheme:schemeInfo.scheme,category:schemeInfo.category,month:row.Report_Month,securityId:isin.value??securityKey(name.value),slug:`${slugify(resolution.displaySecurityName)}-${stableHash(isin.value??name.value).slice(0,8)}`,isin:isin.value,stock:resolution.displaySecurityName,sourceSecurityName:row.Company,canonicalSecurityName:resolution.canonicalSecurityName,nameResolutionStatus:resolution.nameResolutionStatus,sector:row.Industry||null,weight:pct.value,quality:isin.value?'ISIN_VALIDATED':'NAME_ONLY',sourceFile:'holdings_public.csv',sourceRow:rowNumber+2})}
candidates.sort(deterministicSort);const holdings=[],seen=new Map();for(const holding of candidates){const key=`${holding.scheme}|${holding.month}|${holding.isin??securityKey(holding.stock)}`;if(seen.has(key)){stats.duplicateRows++;report.duplicates.push({key,retainedWeight:seen.get(key).weight,duplicateWeight:holding.weight});continue}seen.set(key,holding);holdings.push(holding)}stats.validRows=holdings.length
const expectedMonths=monthsBetween('2025-01','2026-06'),coverage=[],available=new Set(holdings.map(h=>`${h.scheme}|${h.month}`));for(const[scheme]of CORE_SCHEMES)for(const month of expectedMonths)coverage.push({scheme,month,status:available.has(`${scheme}|${month}`)?'AVAILABLE':manifest.months.includes(month)?'MISSING':'SOURCE_NOT_AVAILABLE'})
const present=CORE_SCHEMES.filter(([s])=>holdings.some(h=>h.scheme===s)).map(([s])=>s),missing=CORE_SCHEMES.map(([s])=>s).filter(s=>!present.includes(s)),portfolioTotals=[]
for(const key of[...available].sort()){const split=key.lastIndexOf('|'),scheme=key.slice(0,split),month=key.slice(split+1),total=holdings.filter(h=>h.scheme===scheme&&h.month===month).reduce((s,h)=>s+h.weight,0);portfolioTotals.push({scheme,month,equityTotal:Number(total.toFixed(4)),nonEquityTotal:null,cashOtherTotal:null,representedTotal:Number(total.toFixed(4)),differenceFrom100:Number((100-total).toFixed(4)),status:total<40||total>105?'REQUIRES_REVIEW':'VALID'})}
const latestMonth=[...new Set(holdings.map(h=>h.month))].sort().at(-1),errors=report.schemaErrors.length+report.percentageAnomalies.length,warnings=report.contaminatedNames.length+report.duplicates.length+report.missingIsins.length+coverage.filter(x=>x.status!=='AVAILABLE').length+portfolioTotals.filter(x=>x.status!=='VALID').length,quality=errors?'INVALID':coverage.some(x=>x.status!=='AVAILABLE')?'PARTIAL':warnings?'VALIDATED_WITH_WARNINGS':'VERIFIED'
const metadata={source:'HDFC Mutual Fund official monthly portfolio disclosures (repository extraction)',sourceFile:'holdings_public.csv',asOf:`${latestMonth}-30T23:59:59.000Z`,generatedAt:new Date(manifest.generatedAtUtc).toISOString(),quality,availability:quality==='INVALID'?'unavailable':quality==='PARTIAL'?'partial':'available',recordCount:holdings.length,schemaVersion:'mf-v2',coverageStart:expectedMonths[0],coverageEnd:expectedMonths.at(-1),schemeCount:present.length,holdingCount:holdings.length,validationStatus:errors?'FAILED':'PASSED_WITH_WARNINGS',sourceSha256:stableHash(sourceText)},months=[...new Set(holdings.map(h=>h.month))].sort(),trustMetadata=buildMfTrustMetadata({holdings,stats:{...stats,validationWarnings:warnings,validationErrors:errors},metadata,hasIsinColumn})
for(const month of months)writeJson(path.join(staging,'by-month',`${month}.json`),{schemaVersion:'mf-v2',month,metadata:{...metadata,asOf:`${month}-28T23:59:59.000Z`},schemes:[...new Set(holdings.filter(h=>h.month===month).map(h=>h.scheme))].sort(),holdings:holdings.filter(h=>h.month===month)})
const schemes=CORE_SCHEMES.filter(([s])=>present.includes(s)).map(([scheme,category])=>({scheme,category,slug:slugify(scheme)}));writeJson(path.join(staging,'index.json'),{version:2,schemaVersion:'mf-v2',dataset:'CredoNomics Core Mutual Fund Intelligence',metadata,trustMetadata,years:[2025,2026],months,expectedMonths,firstMonth:months[0],latestMonth,schemes,presentCoreSchemes:present,missingCoreSchemes:missing,counts:{holdings:holdings.length,stocks:new Set(holdings.map(h=>h.securityId)).size,schemes:present.length,amcs:new Set(holdings.map(h=>h.amc)).size},qualityAudit:{sourceRows:stats.sourceRows,selectedCandidateRows:stats.selectedRows,publishedHoldings:holdings.length,isinCoveragePct:trustMetadata.isinCoveragePercent,normalizedCompanyRows:stats.normalizedRows,rejectedRows:stats.rejectedRows,duplicateRows:stats.duplicateRows,validationWarnings:warnings,validationErrors:errors},methodology:{scope:'Six intended HDFC active-equity schemes',securityIdentity:'Exact unique ISIN match to the verified equity instrument master; otherwise the normalized source name is preserved',duplicateHandling:'First deterministic row retained; duplicates reported',missingData:'No interpolation or carry-forward'}})
const latestHoldings=holdings.filter(h=>h.month===latestMonth),previousMonth=months.at(-2)??null;writeJson(path.join(staging,'latest.json'),{schemaVersion:'mf-v2',latestMonth,previousMonth,metadata,summary:{holdings:latestHoldings.length,schemes:new Set(latestHoldings.map(h=>h.scheme)).size},topConsensus:[],signals:{},sectorRotation:[],ownershipMatrix:[]})
const securityIndex=[];for(const securityId of[...new Set(holdings.map(h=>h.securityId))].sort()){const history=holdings.filter(h=>h.securityId===securityId),first=history[0],tracked=[...new Set(history.map(h=>h.month))].sort(),monthlyHistory=tracked.map(month=>{const group=history.filter(h=>h.month===month),totalWeight=group.reduce((s,h)=>s+h.weight,0),schemeCount=new Set(group.map(h=>h.scheme)).size;return{month,schemeCount,totalWeight:Number(totalWeight.toFixed(4)),normalizedWeight:Number((totalWeight/Math.max(1,schemeCount)).toFixed(4)),avgHeldWeight:Number((totalWeight/Math.max(1,group.length)).toFixed(4))}}),latest=history.filter(h=>h.month===tracked.at(-1));const detail={securityId,slug:first.slug,isin:first.isin,stock:first.stock,sector:first.sector??'Unclassified',firstTracked:tracked[0],latestTracked:tracked.at(-1),monthsTracked:tracked.length,maxSchemeCount:Math.max(...monthlyHistory.map(x=>x.schemeCount)),peakNormalizedWeight:Math.max(...monthlyHistory.map(x=>x.normalizedWeight)),latestSchemeWeights:latest.map(h=>({scheme:h.scheme,weight:h.weight,quality:h.quality})).sort((a,b)=>a.scheme.localeCompare(b.scheme)),monthlyHistory,schemeHistory:[...new Set(history.map(h=>h.scheme))].sort().map(scheme=>({scheme,history:history.filter(h=>h.scheme===scheme).map(h=>({month:h.month,weight:h.weight,quality:h.quality}))})),sources:tracked.map(month=>({month,pdfs:['holdings_public.csv']}))};writeJson(path.join(staging,'securities',`${first.slug}.json`),detail);securityIndex.push({securityId,slug:first.slug,isin:first.isin,stock:first.stock,sector:first.sector,latestTracked:tracked.at(-1)})}writeJson(path.join(staging,'securities','index.json'),{securities:securityIndex})
writeJson(path.join(reports,'coverage.json'),{schemaVersion:'mf-v2',expectedSchemes:CORE_SCHEMES.map(x=>x[0]),expectedMonths,matrix:coverage});writeJson(path.join(reports,'rejections.json'),report);writeJson(path.join(reports,'portfolio-totals.json'),portfolioTotals);writeJson(path.join(reports,'scheme-reconciliation.json'),{sourceSchemes:[...new Set(rows.map(r=>r.Scheme))].sort(),generatedSchemes:present,missingSchemes:missing,unexpectedSchemes:[],duplicateSchemes:[],emptySchemes:missing,incompleteSchemes:present.filter(s=>coverage.some(x=>x.scheme===s&&x.status!=='AVAILABLE'))});writeJson(path.join(reports,'summary.json'),{authoritativeSource:{file:'data/mf-production-source/holdings_public.csv',sourceType:'CSV production export',authority:'Derived from HDFC Mutual Fund official portfolio disclosure PDFs',reportingRange:`${manifest.firstMonth} to ${manifest.latestMonth}`,expectedSchemes:CORE_SCHEMES.length,sourceRecords:rows.length},stats:{...stats,schemesFound:present.length,schemesPublished:present.length,monthsExpected:expectedMonths.length,monthsAvailable:months.length,missingSchemeMonthCombinations:coverage.filter(x=>x.status!=='AVAILABLE').length,totalHoldingsPublished:holdings.length,validationErrors:errors,validationWarnings:warnings},quality,contentHash:stableHash(JSON.stringify(holdings))});writeJson(path.join(staging,'.validation.json'),{status:'PASSED',contentHash:stableHash(JSON.stringify(holdings))});console.log(`MF staging generated: ${holdings.length} holdings, ${present.length}/6 schemes, ${stats.rejectedRows} rejected, ${stats.duplicateRows} duplicates.`)
