'use client'

import { ArrowLeft, LineChart, Sparkles, Upload, TrendingUp, TrendingDown, PlusCircle, MinusCircle, Info } from 'lucide-react'
import { useMemo, useState } from 'react'

type Holding={name:string;weight:number}
function parse(text:string):Holding[]{return text.split(/\r?\n/).map(l=>l.trim()).filter(Boolean).map(l=>{const p=l.split(/,|\t/);return{name:(p[0]||'').trim(),weight:Math.max(0,Number((p[1]||'').replace('%','').trim())||0)}}).filter(x=>x.name)}
const prevSample=`HDFC Bank,8.20\nICICI Bank,7.10\nReliance Industries,6.40\nInfosys,4.10\nBharti Airtel,3.20`
const currSample=`HDFC Bank,7.80\nICICI Bank,7.60\nReliance Industries,5.90\nBharti Airtel,4.00\nLarsen & Toubro,2.10`
export default function MFTracker(){
 const [prev,setPrev]=useState(prevSample),[curr,setCurr]=useState(currSample)
 const result=useMemo(()=>{const a=parse(prev),b=parse(curr),am=new Map(a.map(x=>[x.name.toLowerCase(),x])),bm=new Map(b.map(x=>[x.name.toLowerCase(),x]));const keys=Array.from(new Set([...am.keys(),...bm.keys()]));const rows=keys.map(k=>{const p=am.get(k),c=bm.get(k);return{name:c?.name||p?.name||k,previous:p?.weight||0,current:c?.weight||0,change:(c?.weight||0)-(p?.weight||0),status:!p?'New':!c?'Exit':'Held'}}).sort((x,y)=>Math.abs(y.change)-Math.abs(x.change));return{rows,newCount:rows.filter(x=>x.status==='New').length,exitCount:rows.filter(x=>x.status==='Exit').length,increased:rows.filter(x=>x.status==='Held'&&x.change>0.001).length,reduced:rows.filter(x=>x.status==='Held'&&x.change<-0.001).length}},[prev,curr])
 const loadFile=(e:React.ChangeEvent<HTMLInputElement>,setter:(s:string)=>void)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setter(String(r.result||''));r.readAsText(f)}
 return <main className="toolPage"><header className="calcNav wrap"><a className="brand" href="/"><img src="/credonomics-mark.png" alt="" className="brandMark"/><span className="brandWords"><strong>CREDONOMICS</strong><small>Investment Solutions</small></span></a><a className="backLink" href="/#tools"><ArrowLeft size={16}/> Back to tools</a></header>
 <section className="calcHero wrap"><div><div className="eyebrow"><Sparkles size={14}/> Live portfolio comparison</div><h1>MF Portfolio <span>Tracker</span></h1><p>Paste or upload two portfolio snapshots and instantly identify additions, exits, increased weights and reductions.</p></div><div className="calcHeroBadge"><LineChart size={24}/><div><small>Factsheet workflow</small><b>Month-to-month changes</b></div></div></section>
 <section className="trackerShell wrap"><div className="snapshotGrid"><article className="snapshot"><div className="snapshotHead"><div><span className="overline">Previous snapshot</span><h2>Earlier month</h2></div><label className="uploadBtn"><Upload size={15}/> Upload CSV<input type="file" accept=".csv,.txt" onChange={e=>loadFile(e,setPrev)}/></label></div><textarea value={prev} onChange={e=>setPrev(e.target.value)} spellCheck={false}/><small>Format: <b>Stock Name, Weight</b> — one holding per line.</small></article>
 <article className="snapshot"><div className="snapshotHead"><div><span className="overline">Current snapshot</span><h2>Latest month</h2></div><label className="uploadBtn"><Upload size={15}/> Upload CSV<input type="file" accept=".csv,.txt" onChange={e=>loadFile(e,setCurr)}/></label></div><textarea value={curr} onChange={e=>setCurr(e.target.value)} spellCheck={false}/><small>Weights may include or omit the % symbol.</small></article></div>
 <div className="changeSummary"><div><PlusCircle size={18}/><small>New holdings</small><b>{result.newCount}</b></div><div><MinusCircle size={18}/><small>Exited holdings</small><b>{result.exitCount}</b></div><div><TrendingUp size={18}/><small>Weights increased</small><b>{result.increased}</b></div><div><TrendingDown size={18}/><small>Weights reduced</small><b>{result.reduced}</b></div></div>
 <div className="changeTableWrap"><div className="changeTableHead"><span className="overline">Detected changes</span><h2>Portfolio movement</h2></div><div className="changeTable"><div className="tr th"><span>Holding</span><span>Previous</span><span>Current</span><span>Change</span><span>Status</span></div>{result.rows.map(r=><div className="tr" key={r.name}><span><b>{r.name}</b></span><span>{r.previous.toFixed(2)}%</span><span>{r.current.toFixed(2)}%</span><span className={r.change>0?'up':r.change<0?'down':''}>{r.change>0?'+':''}{r.change.toFixed(2)} pp</span><span><em className={`status ${r.status.toLowerCase()}`}>{r.status}</em></span></div>)}</div></div>
 <div className="calcNote trackerNote"><Info size={17}/><p>This tool compares disclosed portfolio weights only. A weight can change because of buying/selling or because market prices changed. Use share counts or transaction disclosures when available before concluding that the fund manager traded a position.</p></div></section>
 <footer className="calcFooter wrap"><p>Use official AMC factsheets or portfolio disclosures for the source data.</p><a href="/">CredoNomics home →</a></footer></main>
}
