import 'server-only'
import type { InstitutionalFlow, MarketPulse, PulseQuote } from '../../domain/market/pulse'
import { buildMarketTrends, buildPulseSummary, classifyBreadth } from '../../domain/market/pulse'
import { calculateQuoteChange, resolvePreviousClose, resolveProviderQuote } from '../../domain/market/quote'
import { upstoxGet } from '../../lib/upstox/client'
import { searchInstrumentMaster } from './instrument-master'

const LIQUID_SYMBOLS=['RELIANCE','HDFCBANK','TCS','BHARTIARTL','ICICIBANK','SBIN','INFY','BAJFINANCE','HINDUNILVR','ITC','LT','HCLTECH','KOTAKBANK','AXISBANK','MARUTI','SUNPHARMA','TITAN','NTPC','M&M','ULTRACEMCO','ONGC','POWERGRID','TATAMOTORS','TATASTEEL','ADANIPORTS','JSWSTEEL','COALINDIA','WIPRO','TECHM','ASIANPAINT']
const SECTORS=[['Nifty Bank','NSE_INDEX|Nifty Bank'],['Nifty IT','NSE_INDEX|Nifty IT'],['Nifty Auto','NSE_INDEX|Nifty Auto'],['Nifty FMCG','NSE_INDEX|Nifty FMCG'],['Nifty Pharma','NSE_INDEX|Nifty Pharma'],['Nifty Metal','NSE_INDEX|Nifty Metal'],['Nifty Realty','NSE_INDEX|Nifty Realty'],['Nifty Financial Services','NSE_INDEX|Nifty Fin Service'],['Nifty PSU Bank','NSE_INDEX|Nifty PSU Bank']] as const
const GLOBALS=[['GIFT NIFTY','GLOBAL_INDEX|SGX NIFTY','120 sec'],['Dow Jones','GLOBAL_INDEX|^DJI','20 sec'],['S&P 500','GLOBAL_INDEX|^GSPC','20 sec'],['US Tech 100','GLOBAL_INDEX|IXIX','20 sec'],['FTSE 100','GLOBAL_INDEX|^FTSE','15 min'],['DAX','GLOBAL_INDEX|^GDAXI','15 min'],['Nikkei 225','GLOBAL_INDEX|^N225','15 min'],['Hang Seng','GLOBAL_INDEX|^HSI','15 min']] as const
const INDICES=[['NIFTY 50','NSE_INDEX|Nifty 50'],['BANK NIFTY','NSE_INDEX|Nifty Bank'],['INDIA VIX','NSE_INDEX|India VIX']] as const
const n=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null
const equities=LIQUID_SYMBOLS.flatMap(symbol=>{const found=searchInstrumentMaster(symbol,10).find(x=>x.exchange==='NSE'&&x.symbol===symbol);return found?[found]:[]})
function quote(raw:Record<string,Record<string,unknown>>|undefined,name:string,symbol:string,key:string):PulseQuote { const item=resolveProviderQuote(raw,key);const ohlc=item?.ohlc as Record<string,unknown>|undefined;const price=n(item?.last_price),previous=resolvePreviousClose(price,n(item?.net_change),n(ohlc?.close));const delta=calculateQuoteChange(price,previous);return{name,symbol,instrumentKey:key,price,change:delta.change,changePercent:delta.changePercent,volume:n(item?.volume),timestamp:typeof item?.timestamp==='string'?item.timestamp:null} }
type FlowResponse={data?:Record<string,Array<{time_stamp?:number;buy_amount?:number;sell_amount?:number}>>}
async function flow(label:'FII'|'DII'):Promise<InstitutionalFlow|null>{try{const raw=await upstoxGet<FlowResponse>(`/v2/market/${label.toLowerCase()}`,{query:{data_type:'NSE_EQ|CASH',interval:'1D'},ttlMs:21_600_000,cacheWhen:value=>Array.isArray((value as FlowResponse).data?.['NSE_EQ|CASH'])&&Boolean((value as FlowResponse).data?.['NSE_EQ|CASH']?.length)});const row=raw.data?.['NSE_EQ|CASH']?.[0];if(!row||!Number.isFinite(row.buy_amount)||!Number.isFinite(row.sell_amount)||!Number.isFinite(row.time_stamp))return null;return{label,segment:'NSE cash',buy:row.buy_amount!,sell:row.sell_amount!,net:row.buy_amount!-row.sell_amount!,timestamp:new Date(row.time_stamp!).toISOString()}}catch{return null}}
export async function getMarketPulse():Promise<MarketPulse>{const domesticKeys=[...equities.map(x=>x.instrumentKey),...SECTORS.map(x=>x[1]),...INDICES.map(x=>x[1])];const globalKeys=GLOBALS.map(x=>x[1]);const getQuotes=(keys:string[],category:string)=>upstoxGet<{data?:Record<string,Record<string,unknown>>}>('/v2/market-quote/quotes',{query:{instrument_key:[...new Set(keys)].join(',')},ttlMs:20_000,cacheWhen:value=>Object.keys((value as {data?:object}).data??{}).length>0,diagnostics:{category,instrumentKey:`${new Set(keys).size} instruments`,recordCount:value=>Object.keys((value as {data?:object}).data??{}).length}});const [domestic,global,flowResults]=await Promise.all([getQuotes(domesticKeys,'market-pulse-domestic'),getQuotes(globalKeys,'market-pulse-global'),Promise.all([flow('FII'),flow('DII')])]);if(!Object.keys(domestic.data??{}).length||!Object.keys(global.data??{}).length)throw new Error('Empty market snapshot');const data={...global.data,...domestic.data};const stocks=equities.map(x=>quote(data,x.companyName,x.symbol,x.instrumentKey)).filter(x=>x.price!==null&&x.changePercent!==null);const sectors=SECTORS.map(([name,key])=>quote(data,name,name,key)).filter(x=>x.price!==null);const globals=GLOBALS.map(([name,key,latency])=>({...quote(data,name,name,key),latency})).filter(x=>x.price!==null);const indices=INDICES.map(([name,key])=>quote(data,name,name,key));const breadth=classifyBreadth(stocks);const flows=flowResults.filter((x):x is InstitutionalFlow=>Boolean(x));return{movers:{gainers:[...stocks].filter(x=>x.changePercent!>0).sort((a,b)=>b.changePercent!-a.changePercent!).slice(0,5),losers:[...stocks].filter(x=>x.changePercent!<0).sort((a,b)=>a.changePercent!-b.changePercent!).slice(0,5),mostActive:[...stocks].filter(x=>x.volume!==null).sort((a,b)=>b.volume!-a.volume!).slice(0,5),universeSize:stocks.length},breadth,sectors,globals,flows,trends:buildMarketTrends(indices,breadth,flows),summary:buildPulseSummary(indices,sectors,breadth),asOf:stocks.find(x=>x.timestamp)?.timestamp??sectors.find(x=>x.timestamp)?.timestamp??null}}
