'use client'

import { ArrowLeft, Fuel, Info, RotateCcw, Sparkles, Gauge, BadgeIndianRupee, ReceiptIndianRupee } from 'lucide-react'
import { useMemo, useState } from 'react'
const inr=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0})
const pct=(n:number)=>`${n.toFixed(2)}%`
function F({label,value,set,prefix,suffix,step=0.1,help}:{label:string,value:number,set:(n:number)=>void,prefix?:string,suffix?:string,step?:number,help:string}){return <label className="calcField"><span className="calcLabel">{label}</span><div className="calcInputWrap">{prefix&&<span>{prefix}</span>}<input type="number" min="0" step={step} value={value} onChange={e=>set(Math.max(0,Number(e.target.value)||0))}/>{suffix&&<span>{suffix}</span>}</div><small>{help}</small></label>}
export default function FuelOptimizer(){
 const d={spend:10000,reward:4,surcharge:1,waiver:1,waiverCap:400,app:0,fee:500};
 const [spend,setSpend]=useState(d.spend),[reward,setReward]=useState(d.reward),[surcharge,setSurcharge]=useState(d.surcharge),[waiver,setWaiver]=useState(d.waiver),[waiverCap,setWaiverCap]=useState(d.waiverCap),[app,setApp]=useState(d.app),[fee,setFee]=useState(d.fee)
 const r=useMemo(()=>{const rewards=spend*reward/100;const charge=spend*surcharge/100;const waiverRaw=spend*waiver/100;const waiverAmt=waiverCap>0?Math.min(waiverRaw,waiverCap):waiverRaw;const appBenefit=spend*app/100;const netMonth=rewards+waiverAmt+appBenefit-charge;const annualGross=netMonth*12;const feeGst=fee*1.18;const annualNet=annualGross-feeGst;const eff=spend>0?annualNet/(spend*12)*100:0;return{rewards,charge,waiverAmt,appBenefit,netMonth,annualGross,feeGst,annualNet,eff}},[spend,reward,surcharge,waiver,waiverCap,app,fee])
 const reset=()=>{setSpend(d.spend);setReward(d.reward);setSurcharge(d.surcharge);setWaiver(d.waiver);setWaiverCap(d.waiverCap);setApp(d.app);setFee(d.fee)}
 return <main className="toolPage"><header className="calcNav wrap"><a className="brand" href="/"><img src="/credonomics-mark.png" alt="" className="brandMark"/><span className="brandWords"><strong>CREDONOMICS</strong><small>Investment Solutions</small></span></a><a className="backLink" href="/#tools"><ArrowLeft size={16}/> Back to tools</a></header>
 <section className="calcHero wrap"><div><div className="eyebrow"><Sparkles size={14}/> Live fuel economics tool</div><h1>Fuel Card <span>Optimizer</span></h1><p>Calculate the true value of a fuel card after rewards, surcharge, waiver limits, app benefits and annual fee.</p></div><div className="calcHeroBadge"><Fuel size={24}/><div><small>Monthly fuel economics</small><b>Savings after costs</b></div></div></section>
 <section className="calcShell wrap"><div className="calcPanel"><div className="calcPanelHead"><div><span className="overline">Your fuel setup</span><h2>Enter current card terms</h2></div><button className="resetBtn" onClick={reset}><RotateCcw size={15}/> Reset</button></div><div className="calcFields">
 <F label="Monthly fuel spend" value={spend} set={setSpend} prefix="₹" step={500} help="Total fuel spend charged to the card."/>
 <F label="Fuel reward value" value={reward} set={setReward} suffix="%" help="Effective reward/cashback percentage on eligible fuel."/>
 <F label="Surcharge charged" value={surcharge} set={setSurcharge} suffix="%" help="Actual fuel surcharge before waiver."/>
 <F label="Surcharge waiver rate" value={waiver} set={setWaiver} suffix="%" help="Percentage waived under the card terms."/>
 <F label="Monthly waiver cap" value={waiverCap} set={setWaiverCap} prefix="₹" step={50} help="Enter 0 if there is no monthly waiver cap."/>
 <F label="Fuel-app / partner extra benefit" value={app} set={setApp} suffix="%" help="Optional extra value from HP Pay or another partner offer."/>
 <F label="Annual fee" value={fee} set={setFee} prefix="₹" step={100} help="Fee before GST; enter 0 if lifetime free."/>
 </div><div className="calcNote"><Info size={17}/><p>Use the effective rupee value of points, not the advertised points multiplier. If your fuel transaction has a minimum/maximum value for surcharge waiver, calculate using the eligible portion only.</p></div></div>
 <aside className="resultPanel"><span className="overline light">Your result</span><div className="bigResult"><small>Effective annual savings rate</small><strong>{pct(r.eff)}</strong><span>after surcharge and annual fee</span></div><div className="resultGrid"><div><small>Net annual value</small><b className={r.annualNet>=0?'positive':'negative'}>{inr.format(r.annualNet)}</b></div><div><small>Net monthly value</small><b>{inr.format(r.netMonth)}</b></div><div><small>Reward value / month</small><b>{inr.format(r.rewards)}</b></div><div><small>Surcharge waiver / month</small><b>{inr.format(r.waiverAmt)}</b></div></div></aside></section>
 <section className="calcInsights wrap"><article><span><Gauge size={18}/></span><small>Surcharge charged</small><b>{inr.format(r.charge)}</b><p>Estimated surcharge before any waiver.</p></article><article><span><BadgeIndianRupee size={18}/></span><small>Partner-app value</small><b>{inr.format(r.appBenefit)}</b><p>Additional monthly benefit entered for a fuel app or partner offer.</p></article><article><span><ReceiptIndianRupee size={18}/></span><small>Annual fee incl. GST</small><b>{inr.format(r.feeGst)}</b><p>Cost deducted from the annual fuel benefits.</p></article></section>
 <footer className="calcFooter wrap"><p>Fuel card terms vary by outlet, transaction size, MCC and issuer policy. Verify the current terms before relying on the result.</p><a href="/">CredoNomics home →</a></footer></main>
}
