'use client'
import { useMemo, useState } from 'react'
import type { CompanyFinancials, FinancialPeriod, FinancialRatio, StatementRow } from '../../../../src/domain/equity/financial-intelligence'
import styles from './financial-intelligence.module.css'

const money = (value: number | null) => value === null ? 'N/A' : `₹${new Intl.NumberFormat('en-IN', { maximumFractionDigits: 1 }).format(value)} Cr`
const number = (value: number | null, suffix = '') => value === null ? 'N/A' : `${new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(value)}${suffix}`
const meaningful = (values: Array<number | null>) => values.some(value => value !== null)
const ratioValue = (ratio: FinancialRatio) => ratio.kind === 'money' ? money(ratio.value) : number(ratio.value, ratio.kind === 'percent' ? '%' : '×')
function Trend({ points, label }: { points: FinancialPeriod[]; label: keyof Pick<FinancialPeriod, 'revenue' | 'operatingProfit' | 'netProfit' | 'eps'> }) {
  const values = points.map(x => x[label]).filter((x): x is number => x !== null); const max = Math.max(...values.map(Math.abs), 1)
  return <div className={styles.chart} aria-label={`${label} financial chart`}>{points.filter(point => point[label] !== null).slice(0, 8).reverse().map(point => { const value = point[label]!; return <div key={point.period} className={styles.barItem}><span className={value < 0 ? styles.negativeBar : ''} title={`${point.period}: ${number(value)}`} style={{ height: `${Math.max(5, Math.abs(value) / max * 100)}%` }} /><small>{point.period.replace('20', "'")}</small></div> })}</div>
}
function PeriodTable({ rows, bank }: { rows: FinancialPeriod[]; bank: boolean }) {
  const columns = [{ key: 'revenue', label: 'Revenue', render: money }, ...(!bank ? [{ key: 'operatingProfit', label: 'Operating profit', render: money }, { key: 'operatingMargin', label: 'Margin', render: (v:number|null) => number(v,'%') }] : []), { key: 'netProfit', label: 'Net profit', render: money }, { key: 'eps', label: 'EPS', render: number }, { key: 'yoy', label: 'YoY', render: (v:number|null) => number(v,'%') }, { key: 'qoq', label: 'QoQ', render: (v:number|null) => number(v,'%') }].filter(column => rows.some(row => row[column.key as keyof FinancialPeriod] !== null))
  return <div className={styles.tableWrap}><table><thead><tr><th>Quarter</th>{columns.map(x => <th key={x.key}>{x.label}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.period}><th>{row.period}</th>{columns.map(column => { const value=row[column.key as keyof FinancialPeriod] as number|null; return <td className={value !== null && value < 0 ? styles.negative : ''} key={column.key}>{column.render(value)}</td> })}</tr>)}</tbody></table></div>
}
function StatementTable({ rows }: { rows: StatementRow[] }) {
  const periods = [...new Set(rows.flatMap(row => row.values.map(v => v.period)))].sort((a,b) => Date.parse(`1 ${b}`)-Date.parse(`1 ${a}`)).slice(0, 6)
  return <div className={styles.tableWrap}><table><thead><tr><th>Particulars</th>{periods.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.slice(0, 18).map(row => <tr key={row.label}><th>{row.label}</th>{periods.map(period => {const value=row.values.find(v => v.period === period)?.value ?? null;return <td className={value !== null && value < 0 ? styles.negative : ''} key={period}>{/^EPS\b/i.test(row.label) ? number(value) : money(value)}</td>})}</tr>)}</tbody></table></div>
}
export default function FinancialIntelligence({ data }: { data: CompanyFinancials }) {
  const [statement, setStatement] = useState<'income' | 'balanceSheet' | 'cashFlow'>('income'); const [frequency, setFrequency] = useState<'quarterly' | 'annual'>('quarterly')
  const points = frequency === 'quarterly' ? data.quarterly : data.annual
  const summary = useMemo(() => Object.entries(data.summary).filter(([, value]) => value !== null), [data.summary])
  const bank = /bank/i.test(`${data.profile.sector ?? ''} ${data.profile.industry ?? ''} ${data.companyName}`); const profitability = data.ratios.filter(x => /ROE|ROCE|ROA|Margin/i.test(x.label) && (!bank || !/margin/i.test(x.label))); const valuation = data.ratios.filter(x => /P\/E|P\/B|EV\/EBITDA|Dividend|Market Cap|Enterprise/i.test(x.label) && (!bank || !/EV\/EBITDA/i.test(x.label)))
  const chartLabels = (['revenue', ...(!bank ? ['operatingProfit'] : []), 'netProfit', 'eps'] as Array<'revenue'|'operatingProfit'|'netProfit'|'eps'>).filter(label => points.some(point => point[label] !== null))
  const navigation = [['financial-summary','Overview'], ['chart','Chart'], ...(chartLabels.length ? [['financial-charts','Financials']] : []), ...(data.quarterly.length ? [['quarterly-results','Quarterly']] : []), ...(valuation.length ? [['valuation','Valuation']] : []), ...(data.peers.length > 1 ? [['peers','Peers']] : []), ...(data.shareholding.length ? [['shareholding-trend','Shareholding']] : []), ['corporate-actions','Corporate Actions']]
  return <div className={styles.intelligence}>
    <nav className={styles.navigator} aria-label="Stock detail sections">{navigation.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>
    {(data.profile.description || data.profile.sector || data.industry) && <section className={styles.section} id="financial-summary"><header><div><span>Verified company metadata</span><h2>Business Snapshot</h2></div><small>Updated {data.asOf ?? 'recently'} · {data.statementType}</small></header><div className={styles.snapshot}><div><b>Sector</b><strong>{data.profile.sector ?? 'N/A'}</strong></div><div><b>Industry</b><strong>{data.profile.industry ?? 'N/A'}</strong></div><div><b>Exchange</b><strong>{data.exchange}</strong></div><div><b>ISIN</b><strong>{data.isin ?? 'N/A'}</strong></div></div>{data.profile.description && <p className={styles.description}>{data.profile.description}</p>}</section>}
    {summary.filter(([key]) => !bank || !['operatingProfit','ebitda','totalDebt'].includes(key)).length > 0 && <section className={styles.section}><header><div><span>Latest annual period</span><h2>Financial Summary</h2></div><small>₹ crore unless stated</small></header><div className={styles.metrics}>{summary.filter(([key]) => !bank || !['operatingProfit','ebitda','totalDebt'].includes(key)).map(([key,value]) => <div key={key}><b>{key.replace(/([A-Z])/g, ' $1').replace(/^./, x => x.toUpperCase())}</b><strong>{key === 'eps' ? number(value) : money(value)}</strong></div>)}</div></section>}
    {meaningful(points.flatMap(x => [x.revenue,x.operatingProfit,x.netProfit,x.eps])) && <section className={styles.section} id="financial-charts"><header><div><span>Reported financial statements</span><h2>Financial Trends</h2></div><div className={styles.switch}>{(['quarterly','annual'] as const).map(x => <button className={frequency === x ? styles.active : ''} onClick={() => setFrequency(x)} key={x}>{x}</button>)}</div></header><div className={styles.charts}>{chartLabels.map(label => <article key={label}><h3>{label.replace(/([A-Z])/g, ' $1')}</h3><Trend points={points} label={label}/></article>)}</div></section>}
    {data.quarterly.length > 0 && <section className={styles.section} id="quarterly-results"><header><div><span>Consolidated reporting</span><h2>Quarterly Results</h2></div></header><PeriodTable rows={data.quarterly.slice(0, 8)} bank={bank}/></section>}
    {Object.values(data.statements).some(rows => rows.length) && <section className={styles.section}><header><div><span>Annual history</span><h2>Annual Financials</h2></div><div className={styles.switch}>{([['income','Income Statement'],['balanceSheet','Balance Sheet'],['cashFlow','Cash Flow']] as const).map(([key,label]) => <button className={statement === key ? styles.active : ''} onClick={() => setStatement(key)} key={key}>{label}</button>)}</div></header><StatementTable rows={data.statements[statement]}/></section>}
    {profitability.length > 0 && <section className={styles.section}><header><div><span>Reported ratios</span><h2>Profitability</h2></div></header><div className={styles.metrics}>{profitability.map(r => <div key={r.key}><b>{r.label}</b><strong>{ratioValue(r)}</strong>{r.sectorValue !== null && <small>Sector {number(r.sectorValue, r.kind === 'percent' ? '%' : '×')}</small>}</div>)}</div></section>}
    {valuation.length > 0 && <section className={styles.section} id="valuation"><header><div><span>Current company and sector values</span><h2>Valuation</h2></div></header><div className={styles.metrics}>{valuation.map(r => <div key={r.key}><b>{r.label}</b><strong>{ratioValue(r)}</strong>{r.sectorValue !== null && <small>Sector {number(r.sectorValue, r.kind === 'percent' ? '%' : '×')}</small>}</div>)}</div></section>}
    {data.peers.length > 1 && <section className={styles.section} id="peers"><header><div><span>Official competitor classification</span><h2>Peer Comparison</h2></div></header><div className={styles.tableWrap}><table><thead><tr><th>Company</th><th>Sector</th><th>P/E</th><th>P/B</th><th>ROE</th><th>ROCE</th></tr></thead><tbody>{data.peers.map(peer => { const get = (match: RegExp) => peer.ratios.find(x => match.test(x.label))?.value ?? null; return <tr className={peer.current ? styles.current : ''} key={peer.instrumentKey}><th>{peer.companyName ?? peer.symbol ?? peer.instrumentKey}</th><td>{peer.sector ?? 'N/A'}</td><td>{number(get(/^P\/E$/i),'×')}</td><td>{number(get(/^P\/B$/i),'×')}</td><td>{number(get(/^ROE$/i),'%')}</td><td>{number(get(/^ROCE$/i),'%')}</td></tr> })}</tbody></table></div><p className={styles.disclaimer}>Peer data is factual and is not a recommendation.</p></section>}
    {data.shareholding.length > 0 && <section className={styles.section} id="shareholding-trend"><header><div><span>Quarterly ownership pattern</span><h2>Shareholding Trend</h2></div></header><div className={styles.tableWrap}><table><thead><tr><th>Quarter</th><th>Promoter</th><th>FII</th><th>DII</th><th>Mutual Funds</th><th>Public / Others</th></tr></thead><tbody>{data.shareholding.slice(0,8).map(row => <tr key={row.period}><th>{row.period}</th><td>{number(row.promoter,'%')}</td><td>{number(row.fii,'%')}</td><td>{number(row.dii,'%')}</td><td>{number(row.mutualFunds,'%')}</td><td>{number(row.public,'%')}</td></tr>)}</tbody></table></div></section>}
  </div>
}
